### ISSUE TITLE
Lavaland cave generation creating turfs with no atmosphere

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21735]
Turfs created by the cave generation system start with an empty gasses list in their air datum (0 Kelvin, 0 kPa) instead of the standard lavaland pressure and airmix. This results in the majority of lavaland being active turfs at round start.
An easy way to see this, is by adding a return on 
https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/air.dm#L275
so the air system doesn't try to force equalize the air, then delay roundstart and check the air on lavaland. The cave generated turfs will all be airless.

@duncathan

**Comment by FantasticFwoosh** [comment]
Golems walk at usual station speeds and watchers can't do ANYTHING in the atmosphere gravity, same as legion heads. Its all dun gone broke.

Please bump up the priority for a fix.

**Comment by Shadowlight213** [comment]
I don't think that's related at all.

**Comment by optimumtact** [comment]
This was fixed by a map pr I believe?

**Comment by Shadowlight213** [comment]
@optimumtact it was not fixed.
The issue isn't in mapping, it's a problem with the cave generation system and atmos.
