### ISSUE TITLE
Discounted uplink gear still costs the full amount if you buy it from elsewhere in the menu

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#28286]
I felt a bit cheated buying a stetchkin for 7tc, only to check the discounted gear section later and see it available for only 3tc

**Comment by msgerbs** [comment]
Almost positive this is fixed.

**Comment by TheBonded** [comment]
> Almost positive this is fixed.

Nope. Go get anything on discount in an uplink, then search for it in the same uplink and see that it costs full price. They only give discount prices in the discount section

**Comment by SethLafuente** [comment]
This seems to have being fixed with the new traitor changes yes 
![Uploading 224217054...]

**Comment by SethLafuente** [comment]
![image](https://user-images.githubusercontent.com/84478872/224220165-241c4c86-22ac-4b53-8c0b-1fad498a60e5.png)

It seems Prog traitor fixed this bug yey

**Comment by Sealed101** [comment]
still an issue, you won't get the discount unless you buy from the discounts menu or through item search
