### ISSUE TITLE
Using up objects (slimecores) in the biobag directly makes the bag appear empty until reopened.

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#30318]
Put in, say, two grey slimecores into a biobag. Inject one with blood, directly from the bag.

The other one will appear to vanish. It'll only reappear if you reopen the bag, dragging it to yourself etc.

This is a big timewaster for xenobiology when they're trying to process a lot of slimecores at once (which is basically every time they're producing monkeys). In an ideal world, it should show one less slime core in that position when you use it.

This may be tied with how slimecores act in regular bags - when you use one up there, it'll remove it from that slot without correcting the other objects in the bag, but only the first instance. So for example, I tend to put a bunch of slimecores in my satchel, then inject the first one, which vanishes from that slot without moving the others. I then inject the second one, and from there I can keep injecting the second slot as the cores I inject get used up and the next one is moved into that slot as normal.

**Comment by XDTM** [comment]
i swear i fixed this

**Comment by AnonymousNow** [comment]
I've been playing xenobiology a lot recently, and it last happened shortly before this issue report went up. It's still happening.

**Comment by bgobandit** [comment]
Is this an issue with all such parent bags?

**Comment by AnonymousNow** [comment]
I can't be sure, as I haven't tried things like B/RPEDs and plant bags in a similar manner. And I'm not sure what parts fit in those that CAN be used up within the bags themselves.
