### ISSUE TITLE
Setting gamemode through game panel gives a no href auth key warning

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#30789]
```
ADMIN LOG: ShizCalev/(ShizCalev) clicked an href with no authorization key!

ADMIN LOG: ShizCalev/(ShizCalev) set the mode as nuclear.

The mode is now: nuclear
```

**Comment by ShizCalev** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
Fixed in #30558

**Comment by ShizCalev** [comment]
@Cyberboss No it's not, this issue report was made days after it was merged. Tested it now on a fresh build and it's still happening lol.

`ADMIN LOG: ShizCalev/(ShizCalev) set the mode as random.

The mode is now: random

ADMIN LOG: ShizCalev/(ShizCalev) clicked an href with no authorization key!`

**Comment by Cyberboss** [comment]
Jesus fucking christ
https://github.com/tgstation/tgstation/blob/62229e5c70cb16b1d27c724547c0caf844727263/code/modules/admin/topic.dm#L1242
Delete this cancer file
