### ISSUE TITLE
Aux base and escape pods are broken.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#36586]
Round ID: 85280

Testmerged: #36388

Make aux base, launch it, only a very little amount of it gets launched, the rest stays. Some players got stuck in hyperspace too apparently.
Not sure if #36483 is the cause.

**Comment by 81Denton** [comment]
I can't repo this on revision 2d4b9568dc2ae253ccf234f0f5c2f626856cbd10 without #36388 merged.
Maybe the testmerged PR is messing with the auxbase/pod areas?

**Comment by 81Denton** [comment]
Ok I was able to repoduce this on @ninjanomnom 's branch. Looks like only the tiles with docking ports get launched and the remaining area gets turned into area/space.

![auxbase-pod](https://user-images.githubusercontent.com/32391752/37736098-4589e980-2d50-11e8-8dee-279e1a71f773.JPG)

**Comment by ninjanomnom** [comment]
Fixed in testmerged pr

**Comment by ShizCalev** [comment]
@ninjanomnom If you're referring to #36388, it's not fixed. Still happening with it testmerged on basil.

**Comment by Shadowflame909** [comment]
This isn't fixed.

**Comment by ninjanomnom** [comment]
The solution to the problem is on the mapping side, the work to convert all shuttles to templates needs to be finished basicaly. Escape pods are fixed but other shuttles may not be if still loaded in on the map directly.

**Comment by DaxDupont** [comment]
@ninjanomnom this is still broken and high priority for things like the steel rain @ShizCalev
