### ISSUE TITLE
syndicate lava base gas miners don't spread gas

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#37064]
![vidyagaems](https://user-images.githubusercontent.com/13092039/38473027-d54ad94e-3b56-11e8-8e39-d89978647445.png)

doesn't update at roundstart until thrown

**Comment by WJohn** [comment]
Looks like #34000 is still around.

**Comment by praisenarsie** [comment]
I swear I saw this in game spreading. This seems to be non-consistent.

**Comment by DingleFlop** [comment]
I HATE THIS ONE. I have died many times busting down the wall just "update" them to get them running.

**Comment by AverageJoe82** [comment]
is this still an issue? it was working locally for me

**Comment by AverageJoe82** [comment]
duplicate #36488

**Comment by SpaceManiac** [comment]
This is fixed as far as I can tell.

**Comment by Cyprex** [comment]
This still happens in the cat surgeon space ruin, please reopen
