### ISSUE TITLE
Plasmaflood Firestarting does not work correctly anymore.

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#38251]
Round ID: Literally any round within the last month.

[Reproduction]: 
Last month and beyond's steps to making a plasmafire:

1. Take plasma canister
2. Release the contents of the canister at max pressure.
3. Throw a lighter/welder/etc into it and watch whatever area you flooded turn into an inferno.
4. (OPTIONAL) add more O2 for a hotter burning fire.

This month's steps to making a plasmafire:

1. Take plasma canister
2. Release contents of the canister at max pressure
3. HAVE A FLAME SOURCE THE TEMPERATURE OF THE GODDAMN SUN OR HOTTER
4. Get a flame for about 10 seconds out of that.
5. Cry because plasmaflooding now is not viable.
6. Use sparks from an igniter+timer assembly instead to heat a room up.

I believe one of the gas or heat refactor/pr was added within the last month may have broken this completely.

**Comment by Tlaltecuhtli** [comment]
this? https://github.com/tgstation/tgstation/pull/37116

**Comment by cyclowns** [comment]
this was fixed in #38230, didnt see this issue earlier

**Comment by Arianya** [comment]
@SpaceManiac This is still happening.

https://gfycat.com/CloseFineBasil

The issue seems to be that for whatever reason the burning gas will extinguish itself, presumably because it's too low temperature. The welder does heat up the gas very slowly over time but until it reaches 100*C it simply won't ignite properly.

**Comment by cyclowns** [comment]
"time but until it reaches 100*C it simply won't ignite properly."
soooo.. how fires are supposed to work? 100C is the ignition temperature of course if its lower than that it wont ignite

**Comment by cyclowns** [comment]
if anything this is just a case of some hotspot_expose calls having their temperature too low

**Comment by Arianya** [comment]
@cyclowns Previous to #37116 Plasma being ignited would stay ignited. I'm not sure if thats a difference in how it decided to stay alight, or if it simply heated to 100*C instantly by nature of plasma burning hotter, but regardless.

Bear in mind that plasma gas is meant to be extremely energetic and volatile. Throwing a welder into a plasma filled room *should* result in a short lived but intense fire even if the gas is currently room temperature.

Also when I say the welder very slowly heats up the gas, I mean it would take one welder in a unventilated room like, 10+ minutes to heat the gas to 100*C, depending on gas volume.

**Comment by cyclowns** [comment]
then someone just needs to tweak the welder's hotspot expose

**Comment by cyclowns** [comment]
also @Arianya 
are you sure you know what #37116 actually did? it fixed an operator precedence error in a define that's only ever utilized in the body of the react() proc for plasma and tritium fires, and for requirement checking in both. its change had an effect on only the former. there is ZERO way that a welder's hotspot_expose would be affected by that change. not to mention I very distinctly remember facing the same 'issue' with the welder not causing plasma fires ages before that PR was ever merged, so no your issue wasn't caused by #37116.

the visual effect you see with the "ignition" isnt actually caused by a fire "not staying ignited" at all, just the hotspot reacting to the welder's hotspot_expose.

**Comment by Arianya** [comment]
@cyclowns I'm not claiming to be an expert on atmos math, just describing the behaviour I'd seen previously vs its present behaviour ¯\_(ツ)_/¯
