### ISSUE TITLE
Loading holodeck syringes into a normal syringe gun and leaving makes the syringe gun fire infinitely.

### ISSUE THREAD

**Issue by Daundra** [tgstation/tgstation#40472]
Round ID: 94412 (at the time of writing the round is ongoing.)
Testmerges: wasn't able to get a commit code.
[Reproduction]: Obtain a normal syringe gun. The one I got was the plain variety from medbay roundstart.
Go to the holodeck. Change the setting to Emergency Medical. There is a holographic box of syringes inside. Load one syringe in your syringe gun. The reagents dont matter, the ones the glitched syringe gun have no reagents. Leave the holodeck. After the point where normally holodeck items on you would disappear, start firing the gun. You can keep firing it infinitely, furthermore, these syringes still do damage so I shot up some things right out the holodeck with infinite syringes. You can unload a syringe but it spits out nothing and "fixes" the gun. An admin I talked about this issue with said it might not be correctly checking to see if the syringe is deleted properly after leaving the holodeck. This seems pretty correct.

Image related. Notice how I was able to break all the tables, windows, and even an airlock (!!) with these dummy broken syringes:
![dreamseeker_2018-09-24_22-56-28](https://user-images.githubusercontent.com/5360736/45990258-53752100-c04d-11e8-80de-ccc444d64dfa.png)

**Comment by GuyonBroadway** [comment]
Congratulations, you built a holographic blaster gun.

We should fix this bug but add a real holo-rifle cus it sounds cool.

**Comment by ATH1909** [comment]
Fun thing you can also do with the holodeck: Flatten a box from the medbay simulation into a sheet of cardboard, then craft that sheet of cardboard back into a box. Congratulations, you now have a non-holographic box that you can take out of the holodeck and which won't disappear when the simulation changes.

**Comment by Garen7** [comment]
This isn't fixed, I was still able to do it on round number 94519. Please reopen this
