### ISSUE TITLE
You can dupe metal and glass with the autholathe

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#43570]
Reproduction:
1)Upgrade autholathe
2)Print an ammo box
3)Remove 1 bullet
4)Insert the box back in to the lathe and get more metal then before.

**Comment by WJohn** [comment]
oh yeah i think i mean to make an issue report on this. metal return numbers are *weird* if you take a single bullet out of the box even once. it changes it completely to count for individual bullets instead of the box as a whole.

**Comment by HomocidlePancakes** [comment]
Wait. WT550 magazines are a thing. I should test it

**Comment by Barhandar** [comment]
it's the speedloader all over again

**Comment by ExcessiveUseOfCobblestone** [comment]
speedloader gave you the exact metal back as it was built regardless of ammo so in that way it "worked".

It's the exact opposite actually, instead of wanting a different formula to use we now want the same one!

honestly you can bandaid it by just minimizing the return to be `min(calculatedamount,normal_ammobox_cost)` (vars i made up)

**Comment by Tlaltecuhtli** [comment]
test

**Comment by TheBonded** [comment]
I'm almost certain this has been fixed, as this bug has been reported in several variants over the years. probably fixed by @Kylerace in https://github.com/tgstation/tgstation/pull/56630 and they missed this issue report in the pr

**Comment by Kylerace** [comment]
@TheBonded as far as im aware this bug still exists and my fix only worked on a subset of the problem. the problem is that contents of created objects are not included in the material cost but can themselves have materials, so the box which costs x units to create and gives x units when recycled contains bullets which cost 0 materials to create and gives y materials when recycled
