### ISSUE TITLE
Prosthetic disappearing upon return from being contractor-abducted

### ISSUE THREAD

**Issue by wabash1** [tgstation/tgstation#52853]
## Round ID:
[143961](https://scrubby.melonmesa.com/round/143961)

## Testmerges:
I can't find the place to look this up in scrubby but I believe it is the following:
#52771: 'fixes arnold pizza not checking for TRAIT_NODISMEMBER' by ShizCalev at commit ba061d2287
#52681: '[Ready] CDN browser assets!' by MrStonedOne at commit a5319b90be

## Reproduction:

Had a sharpened chainsaw on my left arm, got contractor abducted, I kept it in the ninja room, upon return I lost it and it was replaced with a regular arm. This probably applies to regular prosthetics, does not apply to augments, I don't think it applies to regular abductors as they don't strip your stuff on return and I don't believe it applies to gulag either.

**Comment by XDTM** [comment]
If they implanted you with a healing gland, its effect would eject the artificial arm and regrow an organic one. It seems like the most likely scenario here.

**Comment by wabash1** [comment]
> If they implanted you with a healing gland, its effect would eject the artificial arm and regrow an organic one. It seems like the most likely scenario here.

This is for the contractor abductor, not the regular one.

**Comment by XDTM** [comment]
My bad, misread the title

**Comment by JohnFulpWillard** [comment]
Fixed by contractor being removed

**Comment by Thecreative8** [comment]
Since contractor kit is back, can someone please confirm this is still an issue?
