### ISSUE TITLE
Mines are set off by directional lighting

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#55382]
## Reproduction:

1). Grab a  `/obj/effect/mine` of any type
2). Get a light source and turn it on (for your directional lighting of course)
3). Go towards the mine with your handy dandy light
4). Your directional lighting will set off the mine, and can be seen as doing so in the chat feed.

Probably has to do with its triggering check.

**Comment by Dorsisdwarf** [comment]
Should have been fixed by #55643 but I guess not, thanks @Azarak

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/109214938-523d0680-7767-11eb-9a7b-3a8caf82d1be.png)
Still an issue
