### ISSUE TITLE
Bots loaded onto mulebots move the mulebots when they attempt to move

### ISSUE THREAD

**Issue by Misdoubtful** [tgstation/tgstation#56586]
## Reproduction:

1). Be the mulebot
2). Load the bot with a patrol or something
3). Watch it take you for a ride.

Reporter also said monkies cause this but I'm way too tired to test or reproduce this at the moment, just watched it happen and wrote a needlessly long title and report.

**Comment by ATH1909** [comment]
frequent mulebot player here, can confirm that this is a thing. note that this is currently the main reason why you don't set a beepsky strapped to a mulebot to "attack everyone" mode (and why you ask a silicon to set the bot strapped to you to NOT patrol), and that fixing it could have unforeseen consequences.

**Comment by timothymtorres** [comment]
If a mob gets loaded on the mule, it should have the `TRAIT_IMMOBILIZED` set and it should fix this.  I'd recommend checking to see if the mob is being controlled by a player before immobilizing it.

**Comment by SuperNovaa41** [comment]
forcemove is the scurge of this codebase

**Comment by Sealed101** [comment]
is still an issue with simpleanimal bots that don't have a buckle restriction via `can_buckle_to`, i.e. - floorbots. beepskies have the restriction and are thus unable to buckle to the MULE.
