### ISSUE TITLE
Shades seem to have godmode

### ISSUE THREAD

**Issue by RigglePrime** [tgstation/tgstation#61935]
## Round ID:
Sybil, 170816

## Testmerges:
#61440

## Reproduction:
Not completely sure, but shades seem to have godmode for no reason. Might have something to do with getting shaded as a sentient sword, since those gain godmode.

**Comment by Mooshimi** [comment]
This seems to be related to something with the haunted sword the chaplain can have

**Comment by JohnFulpWillard** [comment]
I havent seen this bug pop up in a while so I have no idea if I fixed this or not in https://github.com/tgstation/tgstation/pull/62340

**Comment by moocowswag** [comment]
bug is still active, its apparently caused if the haunted sword is changed/destroyed after being activated but before a ghost is put into it.

**Comment by Sealed101** [comment]
polling for a spirit and destroying the possessed sword before a spirit is made makes the summoned spirit in `null`. you can't really swap to another nullrod type from it, i think, but nullrods aren't really bomb-proof or otherwise protected, so who knows what could happen to them

## relevant code:
https://github.com/tgstation/tgstation/blob/62e5a5058073c219e62eab2141001f7bad6ec77a/code/datums/components/spirit_holding.dm#L49-L86
