### ISSUE TITLE
Engineering Department Order consoles are unable to order gas canisters

### ISSUE THREAD

**Issue by Potato-Masher** [tgstation/tgstation#62883]
## Round ID:
[173159](https://scrubby.melonmesa.com/round/173159) 

## Reproduction:
Attempting to order a gas canister with the engineering order console simply results in the console saying "Something went wrong!" or something similar. Nothing further happens. Perhaps has something to do with the fact canisters don't come shipped in normal crates?

**Comment by BlueMemesauce** [comment]
This was supposed to have been fixed with #62829

**Comment by Potato-Masher** [comment]
Seems like to me that PR was just to ensure that it doesn't break the entirety of cargo if something goes wrong when ordering the canister, and yes this is still an issue.

**Comment by Potato-Masher** [comment]
Gonna open a new one with more details, since this is a bug affecting more than just the order consoles
