### ISSUE TITLE
Permanent Split Personality Not So Permanent

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#63794]
Reporting client version: 514.1571

## Round ID:
[175914](https://scrubby.melonmesa.com/round/175914)

## Testmerges:
- [makes ai static into images added to obscured turfs to save on maptick](https://www.github.com/tgstation/tgstation/pull/63666)
- [Revert "Require Node 16"](https://www.github.com/tgstation/tgstation/pull/63331)
- [lowers kilo's bombcap multiplier](https://www.github.com/tgstation/tgstation/pull/63750)

## Reproduction:
Watch an Ethereal commit _Death_
Wait for the inevitable crystalization, see a split personality prompt!
Take it, expect a shift full of brain split shenanigans- They die.
When they do so, they _Feel Alone Again_, in spite of the (Supposidely) permanent brain trauma?
Everytime they're revived, I get their body re-enter prompt, even if the actual trauma is long gone (this last part's probably just normal post brain split trauma behaviour, but Still)
![image](https://user-images.githubusercontent.com/76874615/147919296-9ead47ce-acc1-4460-94bc-d4d3aa48d35a.png)

Is Brain Split the only trauma exception to the Permanent trauma rule? I 100% heard dChat freak out about it being permanent when it happened, so it's just weird to see it dissapear afterwards. 
![image](https://user-images.githubusercontent.com/76874615/147921351-cd7745ac-a834-42d4-99f2-447415e40dbf.png)
It should either Actually Be Permanent or not say so.

**Comment by RandomGamer123** [comment]
Split personality is unique about how it does not persist after death, looking at the code history this seems to be intended as it qdel-ed the trauma after death since when it was added, but its definitely not documented anywhere unless you codedive.
Normally, ethereal traumas are permanent, but since this doesnt use the normal trauma cure mechanic (eg. neurine / surgery), but rather the trauma qdels itself if the body dies, it bypasses it.

> Everytime they're revived, I get their body re-enter prompt

This part actually seems to be a bug rather than normal post brain split trauma behavior

**Comment by AdipemDragon** [comment]
> Split personality is unique about how it does not persist after death, looking at the code history this seems to be intended as it qdel-ed the trauma after death since when it was added, but its definitely not documented anywhere unless you codedive. 

Oh great, one of the rarer traumas and it just gets Deleted out of existence if gently poked. 
If this is how it's handled, is this also why sometimes it just makes the 2nd personality just Take Over Forever with no ingame way for it to be reversed unless an admin literally just drops the original ghost back into control?
What of the imaginary friend trauma, is it also fragile and drops the second person upon death? (I'll test this for myself later)

Is the whole reason for the dropping just a concern of "Oh, I wouldn't wanna keep a 2nd person tied down to this person"? If so, why not just have it something that's in control of the 2nd person? There's gotta be smarter ways about this than a simple qDel.

> This part actually seems to be a bug rather than normal post brain split trauma behavior

Oh even better, the one thing I've seen is actually consistent, throughout the times I've gotten to be the secondary personality, is an actual bug, fantastic. Or at the very least, a consequince of assigning multiple ghosts to the same mob.


Here's an idea, then. (I don't know where I could even go about putting this out, so I'm just dropping it here)
Why not take inspiration in how other Mob Controlling Something situations are handled, and have this be handled by having a new mob spawn that's tied to the existence of the trauma and that hitches a ride inside the brain item itself that sometimes gets to control the body like a weird mech. Basically, just adding a whole new layer of mob just so the game Wouldn't Not Know what to do with multiple ghosts being assigned to the same mob directly.

**Comment by RandomGamer123** [comment]
> If this is how it's handled, is this also why sometimes it just makes the 2nd personality just Take Over Forever with no ingame way for it to be reversed unless an admin literally just drops the original ghost back into control?

This *should* have been fixed around 6 months ago, have you seen this in any round like within the past 6 months?

**Comment by AdipemDragon** [comment]
> This should have been fixed around 6 months ago, have you seen this in any round like within the past 6 months?

I've personally had to drop someone into their own body, and I've watched someone else get brain split, have it get fixed with the wrong personality in charge, have That one get brain split, and have a 3rd personality take over when it got cured (thanks, brain tumor)

Both this December.

**Comment by Mooshimi** [comment]
> > This should have been fixed around 6 months ago, have you seen this in any round like within the past 6 months?
> 
> I've personally had to drop someone into their own body, and I've watched someone else get brain split, have it get fixed with the wrong personality in charge, have That one get brain split, and have a 3rd personality take over when it got cured (thanks, brain tumor)
> 
> Both this December.

So the bug here should be fixed already. I'll make a note to blacklist the split personality from ethereal since it's not actually permanent and close this issue on that note, since we have a truly large number of issues related to this topic.

**Comment by AdipemDragon** [comment]
Well, that. Doesn't really fix the original issue, rather just sidesteps it, but i guess it's not my call to make, oh well.

**Comment by Mooshimi** [comment]
> Well, that. Doesn't really fix the original issue, rather just sidesteps it, but i guess it's not my call to make, oh well.

You're correct, I'll see about making it so this isn't under the permanent category now that I think of it
