### ISSUE TITLE
lag for anywhere between 5 and 10 seconds when changing z levels

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#72206]
Reporting client version: 514.1589

## Round ID:
196834

## Reproduction:
this shit has been happening for months and it's the most infuriating shit in the world. definitely is not happening to everyone but it's happening to me

**Comment by LemonInTheDark** [comment]
What happens when you disable multiz parallax/effects in general

**Comment by newfren** [comment]
I have disabled parallax and it has done nothing and also since played on tramstation and experienced incredible lag spikes there too, moving even beyond just the z-level changes

**Comment by newfren** [comment]
also, it shows up in chat as ping spikes (on the little readout) but I do not get them on other maps

**Comment by newfren** [comment]
yes

**Comment by newfren** [comment]
setting multiz performance settings from standard to low fixes most of the lag but introduces a lot of fun bugs (everything going white, not being able to click on anything, etc) that can only be fixed by going back to standard then back to low. I have a fairly powerful computer, are those settings actually changing how much data is sent

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/pull/72604 will solve that set of issues (or it ought to)

Multiz eats a lot of gpu because we essentially need to copy and paste our rendering stack for each z level on the map, might be your trouble. It's not a network or data thing it's just what actually needs to be rendered here
I brought up the parallaxing because we need to zoom a lot of plane masters in and out to do the parallaxing effect.
It's possible that this animation, even though it doesn't actually change anything with the parallaxing disabled, is part of your trouble

I'd look at gpu consumption, it might just be that.

**Comment by TheVekter** [comment]
This appears to still be happening as of late March, I don't personally experience this bug though so if newfren could confirm they're still seeing it that'd be rad.
