### ISSUE TITLE
Camera consoles dont work properly on 515

### ISSUE THREAD

**Issue by Autisem** [tgstation/tgstation#79954]
## Round ID: N/A

![afbeelding](https://github.com/tgstation/tgstation/assets/36102060/15972a7e-e603-4836-8220-299786297813)

seems camera consoles are broke on 515(running 515.1620)

## Testmerges:

N/A

## Reproduction:

use camera console on 515 version

**Comment by SyncIt21** [comment]
So it does not work on the latest version of Byond i.e. 515.1620 however it still does work on 515.1609. Since this is a Byond bug don't expect it to be fixed any time soon so as a temporary work around you can ask your server host to download older versions of Byond from [here](http://www.byond.com/download/build/515/). 

515.1609 is the minimum compile version required.

**Comment by dalmationer** [comment]
thanks for the workaround syncit!

**Comment by SyncIt21** [comment]
I think this is fixed with the latest version 515.1623. Can someone confirm?

**Comment by GregariousJB** [comment]
> I think this is fixed with the latest version 515.1623. Can someone confirm?

Not working on 1623, no. Just tested this on a localhost server, started as a Captain, and used the security camera console on the Tramstation bridge - still not working for humans or cyborgs.

I installed Byond 515.1609 as recommended by @SyncIt21, did a clean compile, and the cameras worked fine. 

Also tested good up to 1614, but failed on 1615, just in case that helps with someone seeking to publish a bug report with Mr. Byond about it.
