### ISSUE TITLE
Choiced options in TGUI unfocus the window

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#88885]
### Issue Summary:

repeat of https://github.com/tgstation/tgstation/issues/88857 but only the focus part as the other part of the issue was fixed.

https://github.com/user-attachments/assets/7c635c51-fbed-4f0b-b967-0721f6ec5ec1

### Reproduction Steps:

see issue summary video

**Comment by AyIong** [comment]
Fixed on 516 (Thank's to chromium with nice focus handle)
I don't see the point of wasting time and fixing this for IE. Since this problem is common with all elements with overflow

When you click on element with overflow, even hidden, focus will be stolen by element

**Comment by Sadboysuss** [comment]
> Fixed on 516 (Thank's to chromium with nice focus handle) I don't see the point of wasting time and fixing this for IE. Since this problem is common with all elements which have overflow
> 
> When you click on element with overflow, even hidden, focus will be stolen by element

welp, till we fully transition to 516 it's still an issue sadly
